import {
    DashboardRounded,
    AdminPanelSettingsRounded,
    Payments,
    FolderShared,
    PersonSearch,
    StorageRounded,
    NoteAdd,
    BarChart,
    Apps,
    InboxRounded,
} from "@mui/icons-material";

export const useAppRoutes = [
    {
        name: "Dashboard",
        path: "/superadmin/dashboard/main",
        icon: DashboardRounded,
        children: [
            {
                name: "Main",
                path: "/superadmin/dashboard/main",
                children: [],
                icon: Apps,
            },
            {
                name: "Overview",
                path: "/superadmin/dashboard/overview",
                children: [],
                icon: StorageRounded,
            },
            {
                name: "Create Sale",
                path: "/superadmin/dashboard/create-sale",
                children: [
                    {
                        name: "Project Sale",
                        path: "/superadmin/dashboard/create-sale/project",
                        children: [],
                    },
                    {
                        name: "Rental Sale",
                        path: "/superadmin/dashboard/create-sale/rental",
                        children: [],
                    },
                    {
                        name: "Brokerage Sale",
                        path: "/superadmin/dashboard/create-sale/brokerage",
                        children: [],
                    },
                ],
                icon: NoteAdd,
            },
            {
                name: "View Sales",
                path: "/superadmin/dashboard/view-sales",
                icon: BarChart,
                children: [
                    {
                        name: "Developer",
                        path: "/superadmin/dashboard/view-reports/developer",
                        children: [],
                    },
                ],
            },
        ],
    },
    {
        name: "Management",
        path: "/superadmin/management",
        icon: AdminPanelSettingsRounded,
        children: [],
    },
    {
        name: "Accounting",
        path: "/superadmin/accounting",
        icon: Payments,
        children: [],
    },
    {
        name: "Documentation",
        path: "/superadmin/documentation",
        icon: FolderShared,
        children: [],
    },
    {
        name: "Human Resource",
        path: "/superadmin/human-resource",
        icon: PersonSearch,
        children: [],
    },
    {
        name: "Inbox",
        path: "/superadmin/inbox",
        icon: InboxRounded,
        children: [],
    },
];

export const useCreateSaleSteps = [
    "Client Details",
    "Property/Unit",
    "Upload POT",
];

export const propertyTypes = [
    { id: 1, label: "Condominiums" },
    { id: 3, label: "Commercial" },
    { id: 4, label: "Industrial" },
    { id: 8, label: "Apartment" },
    { id: 9, label: "Beach House" },
    { id: 10, label: "House & Lot" },
    { id: 11, label: "Townhouse" },
    { id: 12, label: "Lot Only" },
    { id: 13, label: "Farm Land" },
    { id: 14, label: "Warehouse" },
    { id: 15, label: "Colombary" },
    { id: 16, label: "Dormitory" },
    { id: 17, label: "Office Space" },
    { id: 18, label: "Parking" },
];

export const condoTypes = [
    { id: 1, label: "Studio" },
    { id: 2, label: "Parking" },
    { id: 3, label: "1 Bedroom" },
    { id: 4, label: "2 Bedroom" },
    { id: 5, label: "3 Bedroom" },
    { id: 6, label: "Loft" },
    { id: 7, label: "Penthouse" },
];

export const commissionStatus = [
    {
        id: 1,
        label: "Unclaimed",
    },
    {
        id: 2,
        label: "Partially Claimed",
    },
    {
        id: 3,
        label: "Fully Claimed",
    },
];

export const countries = [
    { id: "AF", label: "Afghanistan" },
    { id: "AL", label: "Albania" },
    { id: "DZ", label: "Algeria" },
    { id: "AD", label: "Andorra" },
    { id: "AO", label: "Angola" },
    { id: "AG", label: "Antigua and Barbuda" },
    { id: "AR", label: "Argentina" },
    { id: "AM", label: "Armenia" },
    { id: "AU", label: "Australia" },
    { id: "AT", label: "Austria" },
    { id: "AZ", label: "Azerbaijan" },
    { id: "BS", label: "Bahamas" },
    { id: "BH", label: "Bahrain" },
    { id: "BD", label: "Bangladesh" },
    { id: "BB", label: "Barbados" },
    { id: "BY", label: "Belarus" },
    { id: "BE", label: "Belgium" },
    { id: "BZ", label: "Belize" },
    { id: "BJ", label: "Benin" },
    { id: "BT", label: "Bhutan" },
    { id: "BO", label: "Bolivia" },
    { id: "BA", label: "Bosnia and Herzegovina" },
    { id: "BW", label: "Botswana" },
    { id: "BR", label: "Brazil" },
    { id: "BN", label: "Brunei" },
    { id: "BG", label: "Bulgaria" },
    { id: "BF", label: "Burkina Faso" },
    { id: "BI", label: "Burundi" },
    { id: "KH", label: "Cambodia" },
    { id: "CM", label: "Cameroon" },
    { id: "CA", label: "Canada" },
    { id: "CV", label: "Cape Verde" },
    { id: "CF", label: "Central African Republic" },
    { id: "TD", label: "Chad" },
    { id: "CL", label: "Chile" },
    { id: "CN", label: "China" },
    { id: "CO", label: "Colombia" },
    { id: "KM", label: "Comoros" },
    { id: "CG", label: "Congo" },
    { id: "CR", label: "Costa Rica" },
    { id: "HR", label: "Croatia" },
    { id: "CU", label: "Cuba" },
    { id: "CY", label: "Cyprus" },
    { id: "CZ", label: "Czech Republic" },
    { id: "DK", label: "Denmark" },
    { id: "DJ", label: "Djibouti" },
    { id: "DM", label: "Dominica" },
    { id: "DO", label: "Dominican Republic" },
    { id: "EC", label: "Ecuador" },
    { id: "EG", label: "Egypt" },
    { id: "SV", label: "El Salvador" },
    { id: "GQ", label: "Equatorial Guinea" },
    { id: "ER", label: "Eritrea" },
    { id: "EE", label: "Estonia" },
    { id: "ET", label: "Ethiopia" },
    { id: "FJ", label: "Fiji" },
    { id: "FI", label: "Finland" },
    { id: "FR", label: "France" },
    { id: "GA", label: "Gabon" },
    { id: "GM", label: "Gambia" },
    { id: "GE", label: "Georgia" },
    { id: "DE", label: "Germany" },
    { id: "GH", label: "Ghana" },
    { id: "GR", label: "Greece" },
    { id: "GD", label: "Grenada" },
    { id: "GT", label: "Guatemala" },
    { id: "GN", label: "Guinea" },
    { id: "GW", label: "Guinea-Bissau" },
    { id: "GY", label: "Guyana" },
    { id: "HT", label: "Haiti" },
    { id: "HN", label: "Honduras" },
    { id: "HU", label: "Hungary" },
    { id: "IS", label: "Iceland" },
    { id: "IN", label: "India" },
    { id: "ID", label: "Indonesia" },
    { id: "IR", label: "Iran" },
    { id: "IQ", label: "Iraq" },
    { id: "IE", label: "Ireland" },
    { id: "IL", label: "Israel" },
    { id: "IT", label: "Italy" },
    { id: "JM", label: "Jamaica" },
    { id: "JP", label: "Japan" },
    { id: "JO", label: "Jordan" },
    { id: "KZ", label: "Kazakhstan" },
    { id: "KE", label: "Kenya" },
    { id: "KI", label: "Kiribati" },
    { id: "KW", label: "Kuwait" },
    { id: "KG", label: "Kyrgyzstan" },
    { id: "LA", label: "Laos" },
    { id: "LV", label: "Latvia" },
    { id: "LB", label: "Lebanon" },
    { id: "LS", label: "Lesotho" },
    { id: "LR", label: "Liberia" },
    { id: "LY", label: "Libya" },
    { id: "LI", label: "Liechtenstein" },
    { id: "LT", label: "Lithuania" },
    { id: "LU", label: "Luxembourg" },
    { id: "MG", label: "Madagascar" },
    { id: "MW", label: "Malawi" },
    { id: "MY", label: "Malaysia" },
    { id: "MV", label: "Maldives" },
    { id: "ML", label: "Mali" },
    { id: "MT", label: "Malta" },
    { id: "MH", label: "Marshall Islands" },
    { id: "MR", label: "Mauritania" },
    { id: "MU", label: "Mauritius" },
    { id: "MX", label: "Mexico" },
    { id: "FM", label: "Micronesia" },
    { id: "MD", label: "Moldova" },
    { id: "MC", label: "Monaco" },
    { id: "MN", label: "Mongolia" },
    { id: "ME", label: "Montenegro" },
    { id: "MA", label: "Morocco" },
    { id: "MZ", label: "Mozambique" },
    { id: "MM", label: "Myanmar" },
    { id: "NA", label: "Namibia" },
    { id: "NR", label: "Nauru" },
    { id: "NP", label: "Nepal" },
    { id: "NL", label: "Netherlands" },
    { id: "NZ", label: "New Zealand" },
    { id: "NI", label: "Nicaragua" },
    { id: "NE", label: "Niger" },
    { id: "NG", label: "Nigeria" },
    { id: "NO", label: "Norway" },
    { id: "OM", label: "Oman" },
    { id: "PK", label: "Pakistan" },
    { id: "PA", label: "Panama" },
    { id: "PG", label: "Papua New Guinea" },
    { id: "PY", label: "Paraguay" },
    { id: "PE", label: "Peru" },
    { id: "PH", label: "Philippines" },
    { id: "PL", label: "Poland" },
    { id: "PT", label: "Portugal" },
    { id: "QA", label: "Qatar" },
    { id: "RO", label: "Romania" },
    { id: "RU", label: "Russia" },
    { id: "RW", label: "Rwanda" },
    { id: "SA", label: "Saudi Arabia" },
    { id: "SN", label: "Senegal" },
    { id: "RS", label: "Serbia" },
    { id: "SG", label: "Singapore" },
    { id: "SK", label: "Slovakia" },
    { id: "SI", label: "Slovenia" },
    { id: "SB", label: "Solomon Islands" },
    { id: "SO", label: "Somalia" },
    { id: "ZA", label: "South Africa" },
    { id: "KR", label: "South Korea" },
    { id: "ES", label: "Spain" },
    { id: "LK", label: "Sri Lanka" },
    { id: "SE", label: "Sweden" },
    { id: "CH", label: "Switzerland" },
    { id: "SY", label: "Syria" },
    { id: "TW", label: "Taiwan" },
    { id: "TH", label: "Thailand" },
    { id: "TR", label: "Turkey" },
    { id: "UA", label: "Ukraine" },
    { id: "AE", label: "United Arab Emirates" },
    { id: "GB", label: "United Kingdom" },
    { id: "US", label: "United States" },
    { id: "UY", label: "Uruguay" },
    { id: "UZ", label: "Uzbekistan" },
    { id: "VE", label: "Venezuela" },
    { id: "VN", label: "Vietnam" },
    { id: "YE", label: "Yemen" },
    { id: "ZM", label: "Zambia" },
    { id: "ZW", label: "Zimbabwe" },
];
